In [1]:
import numpy as np

## Zero Array

In [3]:
shape = (7,2)
np.zeros(shape,int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [13]:
np.ones((2,2),int)

array([[1, 1],
       [1, 1]])

In [9]:
np.arange(5,10,3)

array([5, 8])

In [14]:
np.full((3,4),45)

array([[45, 45, 45, 45],
       [45, 45, 45, 45],
       [45, 45, 45, 45]])