# This are the practice problems from `Geeks for Geeks` on Numpy Matrix
<a href="https://www.geeksforgeeks.org/python-numpy-practice-exercises-questions-and-solutions/">Numpy Matrix Problems</a>

### Let's Import Numpy first

In [1]:
import numpy as np

### Get the maximum value from given matrix

In [4]:
mat = np.matrix('[3,4,5,6]')
mat.max()

6

### Get the minimum value from given matrix

In [5]:
mat.min()

3

### Find the number of rows and columns of a given matrix using NumPy

In [6]:
mat.shape

(1, 4)

### Select the elements from given matrix

In [12]:
mat.take(3,axis=1)

matrix([[6]])

### Find the sum of value in matrix

In [13]:
mat.sum()

18

### Find the sum of diagonal value of a matrix

In [49]:
# There are two methods to approach this problem

# method : 1 by using .trace function of Numpy

arr = np.array([[5,6,7],[1,2,3],[8,9,0]])

arr.trace()


7

In [48]:
# method : 2 by using .diagonal function of Numpy

sum(arr.diagonal())


7

### Adding and Subtracting Matrices in Python

In [50]:
mat1 = np.array([[5,4,7],[6,4,7],[1,5,8]])
mat2 = np.array([[15,24,70],[61,41,70],[11,15,18]])

mat1 + mat2

array([[20, 28, 77],
       [67, 45, 77],
       [12, 20, 26]])

In [51]:
mat1 - mat2

array([[-10, -20, -63],
       [-55, -37, -63],
       [-10, -10, -10]])

In [57]:
print(np.add(mat1, mat2),end='\n\n')
print(np.subtract(mat1, mat2))

[[20 28 77]
 [67 45 77]
 [12 20 26]]

[[-10 -20 -63]
 [-55 -37 -63]
 [-10 -10 -10]]


### Ways to add row/columns in numpy array

In [66]:
np.vstack((mat1,mat2)).shape

(6, 3)

### Matrix Multiplication in NumPy

In [67]:
np.multiply(mat1, mat2)

array([[ 75,  96, 490],
       [366, 164, 490],
       [ 11,  75, 144]])

### Get the eigen values of a matrix

In [70]:
np.linalg.eigvals(mat2)

array([93.93975723 +0.j        , -9.96987862+10.61779046j,
       -9.96987862-10.61779046j])

### How get a determinant of matrix

In [72]:
np.linalg.det(mat2)

19927.999999999996

### How to get the inverse of a matrix

In [73]:
np.linalg.inv(mat1)

array([[-1.00000000e+00,  1.00000000e+00,  2.96059473e-16],
       [-1.36666667e+01,  1.10000000e+01,  2.33333333e+00],
       [ 8.66666667e+00, -7.00000000e+00, -1.33333333e+00]])

### How to count the frequency of unique values in NumPy array?

In [97]:
mat1

array([[5, 4, 7],
       [6, 4, 7],
       [1, 5, 8]])

In [102]:
# This is hard-coded method
import pandas as pd

# First let's find out occurences at each level
sum1 = np.bincount(mat1[0]) + np.bincount(mat1[1])

# appended 0 to maintain the shape with third row
sum1 = np.append(sum1,[0])

# Again do the sum
sum2 = sum1 + np.bincount(mat1[2])

# Using Pandas Series to accurately show the frequency of each no. occured
pd.Series(sum2, index=range(len(sum2)))

0    0
1    1
2    0
3    0
4    2
5    2
6    1
7    2
8    1
dtype: int64

In [104]:
# method 2 : with the use of Numpy
np.unique(mat1,return_counts=True)

(array([1, 4, 5, 6, 7, 8]), array([1, 2, 2, 1, 2, 1], dtype=int64))

### Multiply matrices of complex numbers using NumPy in Python

In [109]:
cmat1 = np.array([4,5,6,7],dtype=complex)
cmat2 = np.array([5,3,8,4],dtype=complex)

np.vdot(cmat1,cmat2)

(111+0j)

### Compute the outer, inner and cross product of two given vectors using NumPy in Python

In [110]:
np.outer(cmat1,cmat2)

array([[20.+0.j, 12.+0.j, 32.+0.j, 16.+0.j],
       [25.+0.j, 15.+0.j, 40.+0.j, 20.+0.j],
       [30.+0.j, 18.+0.j, 48.+0.j, 24.+0.j],
       [35.+0.j, 21.+0.j, 56.+0.j, 28.+0.j]])

In [111]:
np.inner(cmat1,cmat2)

(111+0j)

In [117]:
# As Cross Product can be implemented only on matrices with dimension greater than 2
cmat1 = cmat1.reshape((2,2))
cmat2 = cmat2.reshape((2,2))

np.cross(cmat1,cmat2)

array([-13.+0.j, -32.+0.j])

### Covariance in numpy

In [118]:
np.cov(mat1,mat2)

array([[  2.33333333,   2.16666667,   3.16666667,  39.83333333,
         20.83333333,   3.16666667],
       [  2.16666667,   2.33333333,   1.33333333,  29.16666667,
         22.66666667,   1.33333333],
       [  3.16666667,   1.33333333,  12.33333333,  93.16666667,
         11.66666667,  12.33333333],
       [ 39.83333333,  29.16666667,  93.16666667, 870.33333333,
        274.83333333,  93.16666667],
       [ 20.83333333,  22.66666667,  11.66666667, 274.83333333,
        220.33333333,  11.66666667],
       [  3.16666667,   1.33333333,  12.33333333,  93.16666667,
         11.66666667,  12.33333333]])

### Getting Correlation from Covariance matrix

In [123]:
np.corrcoef(mat1,mat2)

array([[1.        , 0.92857143, 0.59030128, 0.88392507, 0.91881964,
        0.59030128],
       [0.92857143, 1.        , 0.24854791, 0.64722547, 0.99967576,
        0.24854791],
       [0.59030128, 0.24854791, 1.        , 0.89924393, 0.22380328,
        1.        ],
       [0.88392507, 0.64722547, 0.89924393, 1.        , 0.62760514,
        0.89924393],
       [0.91881964, 0.99967576, 0.22380328, 0.62760514, 1.        ,
        0.22380328],
       [0.59030128, 0.24854791, 1.        , 0.89924393, 0.22380328,
        1.        ]])

### Getting Kronecker Product

In [124]:
np.kron(mat1,mat2)

array([[ 75, 120, 350,  60,  96, 280, 105, 168, 490],
       [305, 205, 350, 244, 164, 280, 427, 287, 490],
       [ 55,  75,  90,  44,  60,  72,  77, 105, 126],
       [ 90, 144, 420,  60,  96, 280, 105, 168, 490],
       [366, 246, 420, 244, 164, 280, 427, 287, 490],
       [ 66,  90, 108,  44,  60,  72,  77, 105, 126],
       [ 15,  24,  70,  75, 120, 350, 120, 192, 560],
       [ 61,  41,  70, 305, 205, 350, 488, 328, 560],
       [ 11,  15,  18,  55,  75,  90,  88, 120, 144]])

In [125]:
mat1.tolist()

[[5, 4, 7], [6, 4, 7], [1, 5, 8]]