# This notebook contains practice questions of `Geeks for Geeks` on Python's `Numpy` module 
<a href="https://www.geeksforgeeks.org/python-numpy-practice-exercises-questions-and-solutions/">Numpy practice Problems</a>

In [1]:
import numpy as np

### How to create empty and full arrays

In [2]:
np.empty((4,5),dtype=int)

array([[        -1,         -1,          0,          0, -243313312],
       [       651,       4096,          0,          0,          0],
       [         0,          0,          0,          0,          0],
       [         0,          0,          0,          0,          0]])

In [3]:
np.full((3,4),34,int)

array([[34, 34, 34, 34],
       [34, 34, 34, 34],
       [34, 34, 34, 34]])

### Create a Numpy array filled of all ones and Zeroes

In [4]:
np.ones((3,4),int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [5]:
np.zeros((3,4),int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### How to Remove rows in Numpy array that contains non-numeric values?

In [6]:
arr = np.array([4,5,6,7,8,np.nan, 23, np.nan])
arr[~np.isnan(arr).any()]

array([], shape=(0, 8), dtype=float64)


It only contains one row hence array got emptied!

In [7]:
arr = np.array([
    [4.0,5.0,6.0],
    [np.nan,23.0, np.nan]
    ])
arr[~np.isnan(arr).any(axis=1)]

array([[4., 5., 6.]])

### Remove single-dimensional entries from the shape of an array

In [8]:
arr = np.array([[[3,4,5],[7,8,9]]])
arr.shape

(1, 2, 3)

In [9]:
arr.squeeze().shape

(2, 3)

### Find the number of occurrences of a sequence in a NumPy array

In [10]:
lis = [[2,8,9,4],
 [9,4,9,4],
 [4,5,9,7],
 [2,9,4,3]]
arr1 = np.array([[2,8,9,4],
 [9,4,9,4],
 [4,5,9,7],
 [2,9,4,3]])
output = repr(arr1).count("9,4")

In [11]:
print(output)

0


### Find the most frequent value in a NumPy array

In [12]:
# method 1
import scipy.stats as sc
arr = np.array([3,4,4,5,6,6,6,20])

sc.mode(arr)

ModeResult(mode=array([6]), count=array([3]))

In [13]:
# method 2
np.bincount(arr).argmax()


6

### Combining a one and a two-dimensional NumPy Array

In [14]:
arr1 = [4,5,6,7]
arr2 = [[9,8,7,6],[6,7,8,9]]

arr1 = np.array(arr1)
arr2 = np.array(arr2)

ndp = np.nditer([arr1, arr2])

for i,j in ndp:
    print("%d:%d" % (i, j),)

4:9
5:8
6:7
7:6
4:6
5:7
6:8
7:9


### How to build an array of all combinations of two NumPy arrays?

In [15]:
num1 = [2,3,4,5]
num2 = [6,7,8,9]

num1 = np.array(num1)
num2 = np.array(num2)

num3 = [[[num1[j],num2[i]] for i in range(num2.shape[0])] for j in range(num1.shape[0])]

In [16]:
# method 1
np.array(num3).reshape(-1,2)

array([[2, 6],
       [2, 7],
       [2, 8],
       [2, 9],
       [3, 6],
       [3, 7],
       [3, 8],
       [3, 9],
       [4, 6],
       [4, 7],
       [4, 8],
       [4, 9],
       [5, 6],
       [5, 7],
       [5, 8],
       [5, 9]])

In [17]:
# method  2
np.array(np.meshgrid(num1,num2)).T.reshape(-1,2)


array([[2, 6],
       [2, 7],
       [2, 8],
       [2, 9],
       [3, 6],
       [3, 7],
       [3, 8],
       [3, 9],
       [4, 6],
       [4, 7],
       [4, 8],
       [4, 9],
       [5, 6],
       [5, 7],
       [5, 8],
       [5, 9]])

### How to compare two NumPy arrays?

In [18]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])

# method1
arr1 == arr2

array([ True,  True,  True,  True,  True])

In [19]:
np.equal(arr1,arr2)

array([ True,  True,  True,  True,  True])

We also have different function like np.greater(a, b), np.less(a,b), np.greater_equal(a, b) etc for different sort of Comparison

### How to check whether specified values are present in NumPy array?

In [20]:
arr = np.array([4,5,6,7])
4 in arr


True

### How to get all 2D diagonals of a 3D NumPy array?

In [21]:
d3_arr = [[
    [4,5,6],
[7,8,9],
[10,11,12]
]]

d3_arr = np.array(d3_arr)
print("Diagonal values: ",d3_arr.diagonal())
print("2D Values: ",d3_arr.shape)

Diagonal values:  [[4]
 [5]
 [6]]
2D Values:  (1, 3, 3)


### Flatten a Matrix in Python using NumPy

In [22]:
arr = [[4,5,6],[7,8,9]]
arr = np.array(arr).ravel()
arr

array([4, 5, 6, 7, 8, 9])

### Flatten a 2d numpy array into 1d array

In [23]:
# Same as above

### Move axes of an array to new positions

In [24]:
arr = np.zeros((1,2,3,4))

np.moveaxis(arr, 2, 1).shape

(1, 3, 2, 4)

### Interchange two axes of an array

In [25]:
arr = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])
np.swapaxes(arr,0,2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

### NumPy – Fibonacci Series using Binet Formula
<img src="https://www.geeksforgeeks.org/wp-content/ql-cache/quicklatex.com-71ff23eb2300b7590d62d57a9058e257_l3.svg" alt="binet_formula">

In [26]:
from math import sqrt

arr = np.arange(1,11)

lengthA = len(arr)

sqrtFive = sqrt(5)

alpha = (1 + sqrtFive)/2
beta = (1 - sqrtFive)/2

binet = np.rint(((alpha**arr) - (beta**arr))/sqrtFive)

print("Hence Fibonacci series of first %d no. is %a"%(lengthA,binet))

Hence Fibonacci series of first 10 no. is array([ 1.,  1.,  2.,  3.,  5.,  8., 13., 21., 34., 55.])


### Counts the number of non-zero values in the array

In [27]:
arr = np.array([3,4,0,0,7,8])

len([x for x in arr if x > 0])

4

For Higher Diemsional Arrays we can  use Numpy's `count_nonzero` function

In [28]:
arr = [[6,7,0],[0,9,8]]
np.count_nonzero(np.array(arr))

4

### Count the number of elements along a given axis

In [29]:
arr = np.array([[4,5,6],[7,9,8]])

In [30]:
np.size(arr,axis=0)

2

In [31]:
np.size(arr,axis=1)

3

We can also implement it through shape property of `Numpy Array`

In [32]:
arr.shape

(2, 3)

### Trim the Starting and trailing zeroes in 1-D Array

In [33]:
arr = np.array([0,0,9,8,7,0])
np.trim_zeros(arr)

array([9, 8, 7])

### Change the datatype of numpy array

In [34]:
arr.astype(float)

array([0., 0., 9., 8., 7., 0.])

### Revere the Numpy array

In [35]:
arr[::-1]

array([0, 7, 8, 9, 0, 0])

Alternatively, we can also use `np.flip` method to reverse an array

### How to make Numpy array read only

In [36]:
import numpy as np
 
a = np.zeros(11)
print("Before any change ")
print(a)
 
a[1] = 2
print("Before after first change ")
print(a)
 
a.setflags(write=False)
print("After making array immutable on attempting  second change ")
a[1] = 7

Before any change 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Before after first change 
[0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
After making array immutable on attempting  second change 


ValueError: assignment destination is read-only