## This are Practice Problem from `Geeks for Geeks`
<a href='https://www.geeksforgeeks.org/python-numpy-practice-exercises-questions-and-solutions/'>Numpy Indexing</a>

In [2]:
import numpy as np

### Replace NumPy array elements that doesn’t satisfy the given condition

In [3]:
#  method : 1

mat = np.array([3,4,5,6,7,8,9])

x = 5

for i,val in enumerate(mat):
    if x > val:
        mat[i] = -1

mat

array([-1, -1,  5,  6,  7,  8,  9])

In [4]:
# method : 2 by Numpy Indexing
mat1 = np.array([3,4,5,6,7,8,9])
mat1[mat1 > 5] = -1

mat1

array([ 3,  4,  5, -1, -1, -1, -1])

### Return the indices of elements where the given condition is satisfied

In [5]:
mat = np.array([5,6,7,8])

# np.where returns index
np.where(mat > 5)

(array([1, 2, 3], dtype=int64),)

### Replace NaN values with average of columns

In [6]:
mat = np.array([[1,np.nan,3,],[np.nan,5,6],[7,8,np.nan]])

np.mean(mat,axis=0)

print("column mean:",np.nanmean(mat,axis=0))
mat[np.where(np.isnan(mat))] = np.nanmean(mat,axis=0)

column mean: [4.  6.5 4.5]


### Replace negative values with zero

In [7]:
neg_arr = np.array([9,8,7,-1])

neg_arr[np.where(neg_arr < 0)] = 0

In [8]:
neg_arr

array([9, 8, 7, 0])

### Find indices of elements equal to zero in a NumPy array

In [9]:
arr = np.array([0,3,4,0,5,6,0])

np.where(arr == 0)

(array([0, 3, 6], dtype=int64),)

### How to Remove columns in Numpy array that contains non-numeric values?

In [10]:
arr23 = np.array([[4,8,5],[np.nan,5,6],[6,5,1],[7,8,9]])

arr23

array([[ 4.,  8.,  5.],
       [nan,  5.,  6.],
       [ 6.,  5.,  1.],
       [ 7.,  8.,  9.]])

In [11]:
# If we want to remove row elements
new_var = np.delete(arr23,np.isnan(arr23).any(axis=1),0)
new_var

array([[4., 8., 5.],
       [6., 5., 1.],
       [7., 8., 9.]])

### How to access different rows of a multidimensional NumPy array?

In [12]:
mat = np.array([[[1,2],[3,4],[5,6]],[[9,8],[8,7],[5,8]]])
mat

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[9, 8],
        [8, 7],
        [5, 8]]])

In [13]:
mat[:,[0]]

array([[[1, 2]],

       [[9, 8]]])

### Get row numbers of NumPy array having element larger than X

In [31]:
arr = np.array([[2,3,4],[5,6,8],[1,5,9]])
arr

array([[2, 3, 4],
       [5, 6, 8],
       [1, 5, 9]])

In [32]:
X = 8

np.where(np.any(arr > X, axis=1))


(array([2], dtype=int64),)

### Get filled the diagonals of NumPy array

In [79]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [66]:
def fill_diagonal(arr, item):
    index = 0
    for i in range(arr.shape[0]):
        arr[i][i] = item
    return arr


fill_diagonal(arr, 4)

array([[4., 1., 1., 1.],
       [1., 4., 1., 1.],
       [1., 1., 4., 1.]])

Numpy also has `fill_diagonal` method 

In [80]:
np.fill_diagonal(arr,3)
print(arr)

[[3. 1. 1. 1.]
 [1. 3. 1. 1.]
 [1. 1. 3. 1.]]


In [81]:
arr

array([[3., 1., 1., 1.],
       [1., 3., 1., 1.],
       [1., 1., 3., 1.]])

### Check elements present in the NumPy array

In [82]:
np.where(np.isin(arr,[3,1]))

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

### Combined array index by index

In [85]:
arr1 = np.array([[12],[23],[45]])
arr2 = np.array([[4],[6],[7]])

np.dstack((arr1,arr2))

array([[[12,  4]],

       [[23,  6]],

       [[45,  7]]])