In [34]:
import numpy as np

# How to create empty and full arrays

In [35]:
np.empty((4,5),dtype=int)

array([[ 727838072,        315,         36,          0,          0],
       [         0,          0,          0,          0,          0],
       [1714775141,  828584249,  895772205,  842280244,  959276641],
       [ 758331440,  875717683, 1701000757, 1650669621,          0]])

In [36]:
np.full((3,4),34,int)

array([[34, 34, 34, 34],
       [34, 34, 34, 34],
       [34, 34, 34, 34]])

# Create a Numpy array filled of all ones and Zeroes

In [37]:
np.ones((3,4),int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [38]:
np.zeros((3,4),int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# How to Remove rows in Numpy array that contains non-numeric values?

In [121]:
arr = np.array([4,5,6,7,8,np.nan, 23, np.nan])
arr[~np.isnan(arr).any()]

array([], shape=(0, 8), dtype=float64)


It only contains one row hence array got emptied!

In [75]:
arr = np.array([
    [4.0,5.0,6.0],
    [np.nan,23.0, np.nan]
    ])
arr[~np.isnan(arr).any(axis=1)]

array([[4., 5., 6.]])

# Remove single-dimensional entries from the shape of an array

In [76]:
arr = np.array([[[3,4,5],[7,8,9]]])
arr.shape

(1, 2, 3)

In [78]:
arr.squeeze().shape

(2, 3)

# Find the number of occurrences of a sequence in a NumPy array

In [103]:
lis = [[2,8,9,4],
 [9,4,9,4],
 [4,5,9,7],
 [2,9,4,3]]
arr1 = np.array([[2,8,9,4],
 [9,4,9,4],
 [4,5,9,7],
 [2,9,4,3]])
output = repr(arr1).count("9,4")

In [106]:
print(output)

4


# Find the most frequent value in a NumPy array

In [118]:
# method 1
import scipy.stats as sc
arr = np.array([3,4,4,5,6,6,6,20])

sc.mode(arr)

ModeResult(mode=array([6]), count=array([3]))

In [120]:
# method 2
np.bincount(arr).argmax()


6

# Combining a one and a two-dimensional NumPy Array

In [139]:
arr1 = [4,5,6,7]
arr2 = [[9,8,7,6],[6,7,8,9]]

arr1 = np.array(arr1)
arr2 = np.array(arr2)

ndp = np.nditer([arr1, arr2])

for i,j in ndp:
    print("%d:%d" % (i, j),)

4:9
5:8
6:7
7:6
4:6
5:7
6:8
7:9


# How to build an array of all combinations of two NumPy arrays?

In [143]:
num1 = [2,3,4,5]
num2 = [6,7,8,9]

num1 = np.array(num1)
num2 = np.array(num2)

num3 = [[[num1[j],num2[i]] for i in range(num2.shape[0])] for j in range(num1.shape[0])]

In [146]:
# method 1
np.array(num3).reshape(-1,2)

array([[2, 6],
       [2, 7],
       [2, 8],
       [2, 9],
       [3, 6],
       [3, 7],
       [3, 8],
       [3, 9],
       [4, 6],
       [4, 7],
       [4, 8],
       [4, 9],
       [5, 6],
       [5, 7],
       [5, 8],
       [5, 9]])

In [147]:
# method  2
np.array(np.meshgrid(num1,num2)).T.reshape(-1,2)


array([[2, 6],
       [2, 7],
       [2, 8],
       [2, 9],
       [3, 6],
       [3, 7],
       [3, 8],
       [3, 9],
       [4, 6],
       [4, 7],
       [4, 8],
       [4, 9],
       [5, 6],
       [5, 7],
       [5, 8],
       [5, 9]])